export const SHOP_DATA = {
  prints: [
    {
      name: "taco",
      title: "Peach of a Treat",
      imgUrl: "/digitalprint1.png",
      price: 20,
      description: "Digital collage made out of vintage magazine cut outs",
      size: `8x10”`,
      priceId: "price_1LNoYqLAv2ONmILvKnqF8X7H",
    },
    {
      name: "cake",
      title: "Early Birds Get the World",
      imgUrl: "/digitalprint2.png",
      price: 20,
      description: "Digital collage made out of vintage magazine cut outs",
      size: "8x10”",
      priceId: "price_1LWNYYLAv2ONmILvuD4CyYPF",
    },
    {
      name: "brunch",
      title: "Taste",
      imgUrl: "/digitalprint3.png",
      price: 20,
      description: "Digital collage made out of vintage magazine cut outs",
      size: "8x10”",
      priceId: "price_1LWNaDLAv2ONmILvClIKXlbP",
    },
    {
      name: "taco",
      title: "Blue World",
      imgUrl: "/digitalprint4.png",
      price: 20,
      description: "Digital collage made out of vintage magazine cut outs",
      size: "8x10”",
      priceId: "price_1LWNb2LAv2ONmILvMoffTQIl",
    },
    {
      name: "cake",
      title: "Graphite Skull",
      imgUrl: "/digitalprint5.png",
      price: 20,
      description: "90 minute skull sketch done with graphite on paper",
      size: "8x10”",
      priceId: "price_1Lbu0VLAv2ONmILviV6J5mI6",
    },
    {
      name: "taco",
      title: "Weird Face",
      imgUrl: "/digitalprint6.png",
      price: 20,
      description:
        "Funky digital illustration with inspiration drawn from the colorful 1960s",
      size: "8x8”",
      priceId: "price_1Lbu1QLAv2ONmILv62HtV6Sh",
    },
    {
      name: "cake",
      title: "Never Been Better Pt. 1",
      imgUrl: "/digitalprint7.png",
      price: 20,
      description: "One of my favorite sayings in my favorite color scheme",
      size: "8x8”",
      priceId: "price_1Lbu2WLAv2ONmILvRq3W3zYH",
    },
    {
      name: "brunch",
      title: "It Is What It Is",
      imgUrl: "/digitalprint8.png",
      price: 20,
      description: "One of my favorite sayings in my favorite color scheme",
      size: "8x8”",
      priceId: "price_1Lbu3fLAv2ONmILv3kEsYv9Q",
    },
    {
      name: "taco",
      title: "Eye of the Moth",
      imgUrl: "/digitalprint9.png",
      price: 20,
      description: "Digital illustration made up of custom tattoo designs",
      size: "8x8”",
      priceId: "price_1Lbu4sLAv2ONmILvKEhA7sKl",
    },
    {
      name: "cake",
      title: "Alive Haha Fuck",
      imgUrl: "/digitalprint10.png",
      price: 20,
      description: "“Live Laugh Love” but with a twist",
      size: "8x8”",
      priceId: "price_1Lbu5eLAv2ONmILvL8ry4efn",
    },
    {
      name: "taco",
      title: "Purple Lady",
      imgUrl: "/digitalprint11.png",
      price: 20,
      description: "Digital collage made out of vintage magazine cut outs",
      size: "8x10”",
      priceId: "price_1Lbu6MLAv2ONmILvU8UIESKw",
    },
    {
      name: "cake",
      title: "Relax Babe",
      imgUrl: "/digitalprint12.png",
      price: 20,
      description: "A calm and comfortable color scheme for a great quote",
      size: "8x10”",
      priceId: "price_1Lbu7MLAv2ONmILv2oNUujUe",
    },
    {
      name: "brunch",
      title: "Flower Boy Twins in Black",
      imgUrl: "/digitalprint13.png",
      price: 20,
      description: "Hand drawn illustration I digitally brought to life",
      size: "8x10”",
      priceId: "price_1Lbu8GLAv2ONmILvzZL6fzgu",
    },
    {
      name: "taco",
      title: "Shut The Fuck Up",
      imgUrl: "/digitalprint14.png",
      price: 20,
      description:
        "Another digital rendition of one of my other favorite sayings, of course",
      size: "8x10”",
      priceId: "price_1Lbu91LAv2ONmILvfZDp8rMM",
    },
    {
      name: "cake",
      title: "Fuck You",
      imgUrl: "/digitalprint15.png",
      price: 20,
      description: "A playful and vibrant color scheme for a great quote",
      size: "8x10”",
      priceId: "price_1Lbu9kLAv2ONmILvE6tCpNN2",
    },
    {
      name: "taco",
      title: "Flower Boy Twins in Teal",
      imgUrl: "/digitalprint16.png",
      price: 20,
      description: "Hand drawn illustration I digitally brought to life",
      size: "8x10”",
      priceId: "price_1LbuAULAv2ONmILvwrY5bBx1",
    },
    {
      name: "cake",
      title: "Taco",
      imgUrl: "/digitalprint17.png",
      price: 20,
      description: "Printed film photographs cut out and collaged",
      size: "8x10”",
      priceId: "price_1LbuBBLAv2ONmILv6IVdMyRy",
    },
    {
      name: "brunch",
      title: "Sunny Side Up",
      imgUrl: "/digitalprint18.png",
      price: 20,
      description: "Digital print of my own acrylic painting",
      size: "8x10”",
      priceId: "price_1LbuCFLAv2ONmILv77ySo3NS",
    },
    {
      name: "taco",
      title: "Red",
      imgUrl: "/digitalprint19.png",
      price: 20,
      description: "Digital print of my own acrylic painting",
      size: "8x10”",
      priceId: "price_1LbuCpLAv2ONmILvPaN2HC2C",
    },
    {
      name: "cake",
      title: "Ice Scream",
      imgUrl: "/digitalprint20.png",
      price: 20,
      description:
        "Digital illustration exemplifying my hate for mint ice cream",
      size: "8x10”",
      priceId: "price_1LbuDaLAv2ONmILvbq0HVee3",
    },
    {
      name: "cake",
      title: "Never Been Better Pt.2",
      imgUrl: "/digitalprint21.png",
      price: 20,
      description: "One of my favorite sayings in my favorite color scheme",
      size: "8x8”",
      priceId: "price_1LbuENLAv2ONmILv8zQrh7PA",
    },
    {
      name: "taco",
      title: "118",
      imgUrl: "/118.png",
      price: 25,
      description: "Digital photograph print taken in Santa Monica",
      size: "8x12”",
      priceId: "price_1LcaxwLAv2ONmILvARLNkb0g",
    },
    {
      name: "cake",
      title: "Abandoned",
      imgUrl: "/abandoned.png",
      price: 25,
      description: "Film photograph print taken within an abandoned factory",
      size: "8x12”",
      priceId: "price_1Lcb0tLAv2ONmILvkRAwHl8c",
    },
    {
      name: "taco",
      title: "Adidas",
      imgUrl: "/adidas.jpg",
      price: 25,
      description: "Digital photograph print of some fresh kicks",
      size: "8x12”",
      priceId: "price_1LcbBOLAv2ONmILvXFK35nQe",
    },
    {
      name: "cake",
      title: "Beach",
      imgUrl: "/beach.png",
      price: 25,
      description:
        "Film photograph print taken at the beach on a crisp, hazy summer day",
      size: "8x12”",
      priceId: "price_1LcbCQLAv2ONmILvq5SvWbpQ",
    },
    {
      name: "taco",
      title: "Boardwalk",
      imgUrl: "/boardwalk.png",
      price: 25,
      description: "Film photograph print of a store front sign in Ocean City",
      size: "8x12”",
      priceId: "price_1LcbDwLAv2ONmILvQglnspLI",
    },
    {
      name: "cake",
      title: "Books",
      imgUrl: "/books.png",
      price: 25,
      description: "Film photograph print taken of a book store in Tampa",
      size: "8x12”",
      priceId: "price_1LcbEjLAv2ONmILvjn3aY74q",
    },
    {
      name: "taco",
      title: "Cigarettes",
      imgUrl: "/cigarettes.png",
      price: 25,
      description: "Film photograph print taken inside an abandoned mansion",
      size: "8x12”",
      priceId: "price_1LcbFaLAv2ONmILvEOwDbyIr",
    },
    {
      name: "cake",
      title: "Corner",
      imgUrl: "/corner.png",
      price: 25,
      description: "Film photograph print taken at an abandoned summer camp",
      size: "8x12”",
      priceId: "price_1LcbGjLAv2ONmILv1I165nbk",
    },
    {
      name: "cake",
      title: "Cowboy",
      imgUrl: "/cowboy.png",
      price: 25,
      description: "Film photograph print taken on the Atlantic City boardwalk",
      size: "8x12”",
      priceId: "price_1LcbHgLAv2ONmILv5o8qoY6y",
    },
    {
      name: "taco",
      title: "Disco Ball",
      imgUrl: "/discoball.png",
      price: 25,
      description:
        "Film photograph print taken from the inside of a disco themed night club",
      size: "8x12”",
      priceId: "price_1LcbIgLAv2ONmILvR77d2jmL",
    },
    {
      name: "cake",
      title: "Hollywood",
      imgUrl: "/hollywood.png",
      price: 25,
      description:
        "Film photograph print taken of a vintage police car on Rodeo Drive",
      size: "8x12”",
      priceId: "price_1LcbNoLAv2ONmILvTGEqlYpo",
    },
    {
      name: "cake",
      title: "Painter",
      imgUrl: "/painter.jpg",
      price: 25,
      description: "Digital photograph taken at a rest stop in Virginia",
      size: "8x12”",
      priceId: "price_1LcbOwLAv2ONmILvdh58yjnd",
    },
    {
      name: "taco",
      title: "Pirate Ship",
      imgUrl: "/pirateship.png",
      price: 25,
      description: "Film photograph print taken off the west coast of Florida",
      size: "8x12”",
      priceId: "price_1LcbPsLAv2ONmILvBcENVlBU",
    },
    {
      name: "cake",
      title: "Playing Games",
      imgUrl: "/playinggames.png",
      price: 25,
      description:
        "Film photograph print taken of an ambitious child playing boardwalk games",
      size: "8x12”",
      priceId: "price_1LcbQwLAv2ONmILvmUv2gei7",
    },
    {
      name: "taco",
      title: "Santa Monica Pier",
      imgUrl: "/santamonica.png",
      price: 25,
      description:
        "Film photograph print taken off the edge of Santa Monica Pier",
      size: "8x12”",
      priceId: "price_1LcbShLAv2ONmILv4HXSpVhQ",
    },
    {
      name: "cake",
      title: "Swing",
      imgUrl: "/swing.png",
      price: 25,
      description:
        "Film photograph print taken outside of an abandoned mansion",
      size: "8x12”",
      priceId: "price_1LcbTfLAv2ONmILvrByyFWr7",
    },
    {
      name: "cake",
      title: "Sway",
      imgUrl: "/swings.png",
      price: 25,
      description: "Film photograph print taken on the Wildwood boardwalk",
      size: "8x12”",
      priceId: "price_1LcbUaLAv2ONmILvr1MP1Rph",
    },
    {
      name: "taco",
      title: "Wavey Davey",
      imgUrl: "/waveydavey.png",
      price: 25,
      description:
        "Film photograph print taken of Glass Animals performance at a music festival",
      size: "8x12”",
      priceId: "price_1LcbVcLAv2ONmILvDRcyiHrm",
    },
    {
      name: "cake",
      title: "Wildwood",
      imgUrl: "/wildwood.png",
      price: 25,
      description:
        "Film photograph print taken on the top of the ferris wheel on the Wildwood boardwalk",
      size: "8x12”",
      priceId: "price_1LcbWoLAv2ONmILv4HG4NqXA",
    },
  ],
  paintings: [
    {
      name: "taco",
      title: "Dont Trip",
      imgUrl: "/donttrip.jpg",
      price: 300,
      description: "Acrylic and oil painting on stretched canvas",
      size: "18x24",
      priceId: "price_1LnXa4LAv2ONmILvwOaQ3ZL5",
    },
    {
      name: "cake",
      title: "Lucky",
      imgUrl: "/lucky.png",
      price: 165,
      description:
        "Mixed media portrait piece created with acrylic paint and assorted textiles",
      size: "8x10”",
      priceId: "price_1LnXbwLAv2ONmILvY0U7MhV1",
    },
    {
      name: "brunch",
      title: "Red",
      imgUrl: "/red.jpg",
      price: 200,
      description: "Acrylic painting on canvas",
      size: "11x14”",
      priceId: "price_1LnXctLAv2ONmILvsOfm9oJV",
    },
    {
      name: "cake",
      title: "Sunny Side Up",
      imgUrl: "/sunnysideup.jpg",
      price: 300,
      description: "Acrylic painting on canvas",
      size: "11x14”",
      priceId: "price_1LnXdkLAv2ONmILvQs54o9jj",
    },
    {
      name: "brunch",
      title: "The Farmer In Distress",
      imgUrl: "/thefarmerindistress.jpg",
      price: 800,
      description: "Acrylic painting on canvas",
      size: "18x24”",
      priceId: "price_1LnXehLAv2ONmILvWjue0CW8",
    },
  ],
};
